CREATE TABLE `table_full` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t_tynyint` tinyint(4) NOT NULL,
  `t_tynyint2` tinyint NOT NULL,
  `t_smallint` smallint(6) NOT NULL,
  `t_mediumint` mediumint(9) NOT NULL,
  `t_int` int(11) NOT NULL,
  `t_tynyint3` tinyint NOT NULL,
  `t_int_unsigned` int(10) unsigned NOT NULL,
  `t_int_unsigned_default` int(10) unsigned NOT NULL DEFAULT '111',
  `t_bigint` bigint(20) NOT NULL,
  `t_decimal` decimal(10,0) NOT NULL,
  `t_float` float NOT NULL,
  `t_double` double NOT NULL,
  `t_real` double NOT NULL,
  `t_date` date NOT NULL,
  `t_datetime` datetime NOT NULL,
  `t_datetime_default` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `t_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `t_ts_no_update` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `t_time` time NOT NULL,
  `t_year` year(4) NOT NULL,
  `t_char` char(10) NOT NULL,
  `t_varchar` varchar(20) NOT NULL,
  `t_binary` binary(30) NOT NULL,
  `t_varbinary` varbinary(40) NOT NULL,
  `t_tinytext` tinytext NOT NULL,
  `t_text` text NOT NULL,
  `t_mediumtext` mediumtext NOT NULL,
  `t_longtext` longtext NOT NULL,
  `t_enum` enum('one','two','three') NOT NULL,
  `t_set` set('one','two','three') NOT NULL,
  `t_text_w_comment` text NOT NULL COMMENT 'Комментарий к текстовому полю',
  PRIMARY KEY (`id`),
  UNIQUE KEY `t_uni` (`id`,`t_tynyint`,`t_smallint`) COMMENT 'Unique key',
  KEY `t_mediumint` (`t_mediumint`),
  KEY `t_tynyint` (`t_tynyint`,`t_smallint`),
  KEY `t_tinytext` (`t_tinytext`(5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4 COMMENT='Сферическая таблица в вакууме';